server:
  port: 8090
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8181
          predicates:
            - Path=/api/**
      default-filters:
        - AddResponseHeader=source, ycx
    nacos:
      discovery:
        server-addr: 127.0.0.1:8849
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
      scg:
        fallback:
          content-type: application/json
          mode: response
          response-status: 200
          response-body: '{"code":0,"message":"系统繁忙，请稍后再试...","data":null}'

dubbo:
  application:
    name: dubbo-springboot-consumer
    qos-enable: false
  consumer:
    timeout: 2000
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8849
